-- Creative Vision / Supabase database schema
-- Run this file in Supabase Dashboard -> SQL Editor.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text unique not null,
  role text not null default 'student'
    check (role in ('student', 'leader', 'admin')),
  created_at timestamptz not null default now()
);

create table if not exists public.weeks (
  id bigint generated by default as identity primary key,
  week_number integer unique not null check (week_number > 0),
  meeting_date date not null,
  meeting_time text not null,
  topic text not null,
  preparation text not null,
  week_title text not null,
  week_body text not null,
  week_status text not null,
  project_title text not null,
  project_percent integer not null default 0
    check (project_percent between 0 and 100),
  project_explanation text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.deadlines (
  id bigint generated by default as identity primary key,
  week_id bigint not null references public.weeks(id) on delete cascade,
  title text not null,
  deadline_date text not null,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.announcements (
  id bigint generated by default as identity primary key,
  announcement_date text not null,
  text text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.resources (
  id bigint generated by default as identity primary key,
  resource_type text not null
    check (resource_type in ('video', 'slide', 'reference')),
  lesson text not null,
  objective text not null,
  title text not null,
  url text,
  storage_path text,
  published boolean not null default false,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create index if not exists deadlines_week_id_idx on public.deadlines(week_id);
create index if not exists resources_type_order_idx on public.resources(resource_type, sort_order);

alter table public.profiles enable row level security;
alter table public.weeks enable row level security;
alter table public.deadlines enable row level security;
alter table public.announcements enable row level security;
alter table public.resources enable row level security;

-- Publicly readable content policies. These are suitable for the initial prototype.
drop policy if exists "Public can read weeks" on public.weeks;
create policy "Public can read weeks"
  on public.weeks for select
  using (true);

drop policy if exists "Public can read deadlines" on public.deadlines;
create policy "Public can read deadlines"
  on public.deadlines for select
  using (true);

drop policy if exists "Public can read announcements" on public.announcements;
create policy "Public can read announcements"
  on public.announcements for select
  using (true);

drop policy if exists "Public can read published resources" on public.resources;
create policy "Public can read published resources"
  on public.resources for select
  using (published = true);

-- Users can read their own profile. Role-management policies will be added later.
drop policy if exists "Users can read own profile" on public.profiles;
create policy "Users can read own profile"
  on public.profiles for select
  to authenticated
  using (auth.uid() = id);

-- This trigger creates a profile whenever a Supabase Auth user signs up.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, email)
  values (new.id, new.email)
  on conflict (id) do update set email = excluded.email;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
